### ISSUE TITLE
Can't compile it on MACOS Ventura

### ISSUE THREAD

**Issue by urmelchen2705** [ladislavb/homebrew-therion#10]
I'm getting this error: 
brew install therion
Error: invalid attribute for formula 'therion': version ("")
/opt/homebrew/Library/Homebrew/formula.rb:294:in `validate_attributes!'
/opt/homebrew/Library/Homebrew/formula.rb:219:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:308:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:308:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:634:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:630:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:630:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:307:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:150:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:97:in `<main>'

**Comment by ladislavb** [comment]
Hi, just update my formula for therion 6.1.5. Everything works as expected on my laptop (MPB 14, M1 Pro, Ventura 13.1). Please test again and share more details about your setup / run 'brew install therion' command with -v parameter (verbose).

**Comment by ladislavb** [comment]
Sorry, closed by mistake...

**Comment by urmelchen2705** [comment]
Working now! Thank you
