### ISSUE TITLE
no usable coordinate transformation found

### ISSUE THREAD

**Issue by pvernant** [ladislavb/homebrew-therion#11]
I have proj 9.2.1 installed but the therion.log is the following, seems that the proj library isn't found, maybe that's just my setup: 
therion 6.1.5 (2022-12-30)
  - using Proj 9.2.1, compiled against 9.2.1
checking optional fonts csr10 csti10 csbx10 csss10 csssi10 ... OK
checking optional fonts cmcyr10 cmcti10 cmcbx10 cmcss10 cmcssi10 ... OK
configuration file: besses.thconfig
reading ... done
reading source files ... done
preprocessing database ... 
therion: error -- no usable coordinate transformation found
writing xtherion file ... done

**Comment by ladislavb** [comment]
Should be fixed in Therion 6.1.8. Please upgrade - the formulae was just updated to install 6.1.8.
