### ISSUE TITLE
macOS Catalina 10.15.6 installation problem

### ISSUE THREAD

**Issue by fratnike** [ladislavb/homebrew-therion#2]
Hi,

   I have followed all the instruction and also tried the manual installation but I receive a compiling error...

Any Idea?

Thank you in advance for your help

enrico

enricof@icts-enrico ~ % brew install https://raw.githubusercontent.com/ladislavb/homebrew-therion/master/therion.rb
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 3 formulae.

Warning: Calling Non-checksummed download of therion formula file from an arbitrary URL is deprecated! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
######################################################################## 100.0%
==> Cloning https://github.com/therion/therion.git
Updating /Users/enricof/Library/Caches/Homebrew/therion--git
==> Checking out revision 8b062cb
HEAD is now at 8b062cb Merge pull request #235 from rsevero/move_curtains_to_uis
HEAD is now at 8b062cb Merge pull request #235 from rsevero/move_curtains_to_uis
==> make config-macosx
==> make
Last 15 lines from /Users/enricof/Library/Logs/Homebrew/therion/02.make:
s/type1/public/amsfonts/cm/cmr7.pfb></usr/local/texlive/2020/texmf-dist/fonts/t
ype1/public/amsfonts/cm/cmr8.pfb></usr/local/texlive/2020/texmf-dist/fonts/type
1/public/amsfonts/cm/cmssdc10.pfb></usr/local/texlive/2020/texmf-dist/fonts/typ
e1/public/amsfonts/cm/cmsy10.pfb></usr/local/texlive/2020/texmf-dist/fonts/type
1/public/amsfonts/cm/cmsy7.pfb></usr/local/texlive/2020/texmf-dist/fonts/type1/
public/amsfonts/cm/cmti10.pfb></usr/local/texlive/2020/texmf-dist/fonts/type1/p
ublic/amsfonts/cm/cmti12.pfb></usr/local/texlive/2020/texmf-dist/fonts/type1/pu
blic/amsfonts/cm/cmti8.pfb></usr/local/texlive/2020/texmf-dist/fonts/type1/publ
ic/amsfonts/cm/cmtt10.pfb></usr/local/texlive/2020/texmf-dist/fonts/type1/publi
c/amsfonts/cm/cmtt12.pfb></usr/local/texlive/2020/texmf-dist/fonts/type1/public
/archaic/givbc10.pfb></usr/local/texlive/2020/texmf-dist/fonts/type1/hoekwater/
mflogo-font/logo10.pfb>
Output written on thbook.pdf (85 pages, 741314 bytes).
Transcript written on thbook.log.
perl ../makefile.pl rm ./thbook.log

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:226:in `<main>'
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:137:in `install'
	21: from /usr/local/Homebrew/Library/Homebrew/utils.rb:494:in `with_env'
	20: from /usr/local/Homebrew/Library/Homebrew/build.rb:142:in `block in install'
	19: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1180:in `brew'
	18: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2153:in `stage'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:82:in `stage'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:107:in `unpack'
	14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `mktemp'
	13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
	12: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
	11: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
	10: from /usr/local/Homebrew/Library/Homebrew/resource.rb:198:in `block in mktemp'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:112:in `block in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2173:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:494:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2174:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1187:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:174:in `block (2 levels) in install'
	 3: from /Users/enricof/Library/Caches/Homebrew/Formula/therion.rb:35:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1963:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1963:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2025:in `block in system': Failed executing: make (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:38:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:153:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:403:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:349:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:353:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:305:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)

**Comment by m0kes** [comment]
I ran into the very same issue, same traceback. Using the most current source of therion (`--HEAD`) does not solve the issue :-(
