### ISSUE TITLE
Error: Calling Non-checksummed download of therion formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.

### ISSUE THREAD

**Issue by m0kes** [ladislavb/homebrew-therion#3]
executing the command `brew install https://raw.githubusercontent.com/ladislavb/homebrew-therion/master/therion.rb` on MacOS 10.15.6 with Homebrew 2.5.2-13-ge082da4 fails with this error message:

```Calling Non-checksummed download of therion formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.```

How can this be fixed?

**Comment by dolerite** [comment]
Exactly the same problem and error message attempting installation on MacOS10.13.6

Please advise!

**Comment by m0kes** [comment]
Even with MacOS Big Sur (11.0.1) it is not working - error message is the same, please fix

**Comment by cmagnuson** [comment]
I had the same issue, resolved with 
`brew tap ladislavb/homebrew-therion`
`brew install therion`

I'd suggest updating the README to those steps.

**Comment by dolerite** [comment]
Thank you cmagnuson, but this had no effect. The first command issued successfully. The second, brew install therion, failed with the same message. Along with:
Error: You are using macOS 10.13. We (and Apple) do not provide support for this old version. You will encounter build failures with some formulae.

**Comment by dolerite** [comment]
Thank you again cmagnuson. The installation page has now been updated to the Therion release for the latest homebrew version 5.5.3. Following the instructions now works, even on my Mac OS 10.13.  I did first install the latest Xcode that can be run with my Mac (Xcode 10.1 from Apple), although I'm not sure this was critical.

**Comment by dolerite** [comment]
I'm now trying to install Therion on MacMini(M3), OS11.1. All is ok up to and including the step
		> brew install therion
which gets as far as "make", but then gives the error output below.

Exactly the same if I use instead:
		> brew install --HEAD therion
Any guidance much appreciated.
Tnx
=======
	Last 15 lines from /Users/michael/Library/Logs/Homebrew/therion/02.make:
	In file included from utest-main.cxx:2:
	extern/catch2/catch.hpp:8205:13: error: invalid operand
          		CATCH_BREAK_INTO_DEBUGGER();
       	  ^
	extern/catch2/catch.hpp:7916:83: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
     	   #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
     			                                                              ^
	extern/catch2/catch.hpp:7881:34: note: expanded from macro 'CATCH_TRAP'
		#define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
 			                      ^
	<inline asm>:1:6: note: instantiated into assembly here
			      int $3
			            ^
	2 errors generated.
	make: *** [utest-main.o] Error 1
	Do not report this issue to Homebrew/brew or Homebrew/core!
	These open issues may also help:
	issue un make (I don't now if is a Therion issue) https://github.com/ladislavb/homebrew-therion/issues/6
	Error: Calling Non-checksummed download of therion formula file from an arbitrary URL is disabled! 
	Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead. 
=== end

**Comment by Andreas-104** [comment]
Hello everyone, 

i have exactly the same Error on my Mac (12.0.1). Can some pls help? 

thanks 
Andreas

**Comment by ladislavb** [comment]
This formulae is using CMAKE now. Please test again.

**Comment by ladislavb** [comment]
I am closing this issue now. If you have problem with the new version of formula (using CMAKE) feel free to open new issue.
