### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lightsomedog** [ladislavb/homebrew-therion#4]
hi all, 

try to install. get this message.

https://github.com/therion/therion.git", :revision => "8b062cb"
>   version "5.4.4+8b062cb
-bash: https://github.com/therion/therion.git, :revision => 8b062cb
  version 5.4.4+8b062cb: No such file or directory

Error: Calling Non-checksummed download of therion formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.

try the bleeding edge ,...

brew install --HEAD https://raw.githubusercontent.com/ladislavb/homebrew-therion/master/therion.rb

Calling Non-checksummed download of therion formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.

so there something wrong and i'm only a user so this above my ,...
i work on a MacOS High Sierra 10.13.6

Lightsomedog

**Comment by cmagnuson** [comment]
@lightsomedog the Non-checksummed download looks to be the same issue as #3 which I just commented a solution for
