### ISSUE TITLE
problem en survey statistics for duplicate survey

### ISSUE THREAD

**Issue by Bergil06** [ladislavb/homebrew-therion#8]
I noticed that survey statistics on the survey generated (the pdf) count all data which are on survey flaged "flags duplicated", but if you put "flags surface", it is not counted on the stats. In the documentation, it is written that flas duplicated are like flags surface : not counted on the stats of survey.
I try on a Therion release of 2019 and on the last available release of 2022.
Here my test files. Re-activate the stats on the survey, I remove it. The survey is on "flag surface".
Thanks

[enclot.zip](https://github.com/ladislavb/homebrew-therion/files/8546552/enclot.zip)

**Comment by ladislavb** [comment]
Hi @Bergil06, sorry, I am not able to help you as this repository contains only homebrew formulae to install Therion on macOS devices. Please report your issue to https://github.com/therion/therion. Thank you.
