### ISSUE TITLE
specifi symbol-point not shown in final survey

### ISSUE THREAD

**Issue by Bergil06** [ladislavb/homebrew-therion#9]
I want to have in my survey the station point "fixed", but not all the others
so in my thconfig.txt file I put :
  symbol-hide point station
  symbol-show point station:fixed
But no point station appeared in my pdf survey. 
If I put : 
    symbol-show point station
All point station (normal and fixed station) appears in my final pdf.
I do not succeed to have only station point flaged "-subtype fixed"
I thinks it's a bug.
Thanks

**Comment by ladislavb** [comment]
Hi @Bergil06, sorry, I am not able to help you as this repository contains only homebrew formulae to install Therion on macOS devices. Please report your issue to https://github.com/therion/therion. Thank you.
